### ISSUE TITLE
Gulp errors out on laravel-elixir dependency

### ISSUE THREAD

**Issue by edbentinck** [laravel/elixir#533]
Another gulp issue, among the many others posted on here.

#### My setup:
- **Node:** v5.11.0 (using nvm)
- **npm:** 3.8.6
- **gulp:** 3.9.1

#### Installed packages:
```
├── bootstrap-sass@3.3.6
├── debug-log@1.0.0
├── gulp@3.9.1
├── gulp-concat@2.6.0
├── gulp-concat-sourcemap@1.3.1
├── gulp-filter@1.0.2
├── gulp-if@1.2.5
├── gulp-jshint@1.12.0
├── gulp-minify-css@0.3.13
├── gulp-ng-annotate@1.1.0
├── gulp-ng-config@1.3.1
├── gulp-notify@2.2.0
├── gulp-sourcemaps@1.6.0
├── gulp-uglify@1.5.3
├── jshint-stylish@2.2.0
├── laravel-elixir@3.4.3
├── laravel-elixir-livereload@1.1.3
└── main-bower-files@2.13.1
```

#### Error when running gulp:
`Cannot find module 'laravel-elixir/node_modules/gulp-util'`

All my problems seem to have begun when I upgraded node to v6.2.0. Little did I realise all hell would break loose.

Running gulp in one of my laravel projects would display an error about needing to rebuild node-sass (`npm rebuild node-sass`). No problem. Some of my other projects have required this recently too, and they still work just fine.

Anyway, along the way I had to delete all my node modules and re-install them. Since then I can't run `gulp` at all.

#### Here is the complete error:
```
module.js:341
    throw err;
    ^

Error: Cannot find module 'laravel-elixir/node_modules/gulp-util'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/MAMP/htdocs/l5talentia/tasks/env_config.task.js:5:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

It appears that not all of laravel-elixir's dependencies are being installed. Any ideas why that would be?

I've tried all sorts, to no avail. `rm -rf node_modules && npm install`, switching versions of node etc. without success. I even tried browsing to the laravel-elixir directory and `npm install`ing manually, but that merely caused gulp to tell me that I am missing a 'default' task from gulpfile.js.

**Comment by JeffreyWay** [comment]
Try a couple things:

1. Upgrade your Elixir version to 5.x.
2.  Remove the laravel-elixir-livereload extension, and see if changes the error.

**Comment by cbtech** [comment]
I was having the same issue. 

For me it turned out that npm was running out of memory.

I was using a 512MB Digital Ocean droplet. I created a 2GB swap file and I could then run `npm install` successfully.

**Comment by edbentinck** [comment]
Thanks for the suggestions, guys.

I managed to fix this after finding a bad reference in some old code of ours. Seems it used to work but not any more. Closing 👍
